// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWzL3KBBYCZggiK4brD1Fy7aZxtJanHJc',
    appId: '1:1013762676213:android:bf7f94ef51408117cabcbc',
    messagingSenderId: '1013762676213',
    projectId: 'co-opsmart',
    storageBucket: 'co-opsmart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBifSopJUFYvH3Wm3SRE_WiONuGparVW1c',
    appId: '1:1013762676213:ios:9a38308c88053883cabcbc',
    messagingSenderId: '1013762676213',
    projectId: 'co-opsmart',
    storageBucket: 'co-opsmart.appspot.com',
    androidClientId: '1013762676213-qf6kkgv9tn5mnd03ohvrmhqhh955sofo.apps.googleusercontent.com',
    iosClientId: '1013762676213-bi66je868qpo5a1m9kol7ecbhriuq94p.apps.googleusercontent.com',
    iosBundleId: 'com.step.bank.step',
  );
}
